#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("PyzeAndroidSample.Resource", IsApplication=true)]

namespace PyzeAndroidSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int bottom_text_blur_height = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int in_app_body_text_size = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int in_app_bottom_bar_padding = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int in_app_button_margin = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int in_app_button_text_size = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int in_app_image_height = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int in_app_layout_width = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int in_app_text_padding = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int in_app_title_text_size = 2131034120;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_keyboard_arrow_left_black_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_keyboard_arrow_right_black_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int in_app_round_corner = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int rounded_button = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int bottom_bar_container_0 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int btn_container = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int btn_next = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int btn_previous = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int counter_textview = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int firstButton = 2131165190;
			
			// aapt resource value: 0x7f07000e
			public const int headerTextview = 2131165198;
			
			// aapt resource value: 0x7f07000b
			public const int headerTextview1 = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int in_app_image_download_progress = 2131165197;
			
			// aapt resource value: 0x7f070003
			public const int in_app_outer_space = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int in_app_scroll_view = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int mainImage = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int msgTextview = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int myButton = 2131165200;
			
			// aapt resource value: 0x7f070007
			public const int secondButton = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int thirdButton = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int topImageview = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int bottom_bar_layout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fragment_in_app_notification_layout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int _inappmessages = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int _of_ = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int app_name = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int hello = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int showing_ = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int tab_new = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int tab_previous = 2131099652;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
